name: Build for M1 and Intel

on: 
  push:
    branches:
      - release
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin x86_64-apple-darwin
        
    - name: Install dependencies
      run: yarn

    - name: Build for M1  
      run: yarn tauri build --target aarch64-apple-darwin

    - name: Build for Intel
      run: yarn tauri build --target x86_64-apple-darwin
    - uses: actions/upload-artifact@v2
      with:
        name: build-Intel
        path: src-tauri/target/x86_64-apple-darwin/release
        
    - uses: actions/upload-artifact@v2  
      with:
        name: build-M1
        path: src-tauri/target/aarch64-apple-darwin/release