name: Build for M1 and Intel

on: 
  push:
    branches:
      - release
  pull_request:

jobs:

  build:
    env:
      APP_VERSION: 1.0.0 
      BUILD_TYPE: release

    runs-on: macos-latest
    
    steps:
    
    - name: Print env
      run: |
        echo "App version is ${APP_VERSION}"
        echo "Build type is ${BUILD_TYPE}"
    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with: 
        targets: aarch64-apple-darwin x86_64-apple-darwin

    - name: Install dependencies  
      run: yarn

    - name: Build for Apple Silicon
      run: yarn tauri build --target aarch64-apple-darwin

    - name: Create artifacts
      run: |
        mkdir artifacts
  
        mv src-tauri/target/aarch64-apple-darwin/release/bundle artifacts/apple-silicon
    
    - uses: actions/upload-artifact@v2
      with:
        name: macos-builds
        path: artifacts