name: Build for M1 and Intel

on: 
  push:
    branches:
      - release
  pull_request:

jobs:

  build:
  
    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Install Xcode tools
      run: xcode-select --install

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with: 
        targets: aarch64-apple-darwin x86_64-apple-darwin

    - name: Install dependencies  
      run: yarn

    - name: Build for Intel
      run: yarn tauri build --target x86_64-apple-darwin

    - name: Build for Apple Silicon
      run: yarn tauri build --target aarch64-apple-darwin

    - name: Create artifacts
      run: |
        mkdir artifacts
        mv src-tauri/target/x86_64-apple-darwin/release artifacts/intel
        mv src-tauri/target/aarch64-apple-darwin/release artifacts/apple-silicon
    
    - uses: actions/upload-artifact@v2
      with:
        name: macos-builds
        path: artifacts